### ISSUE TITLE
Deriving Via

### ISSUE THREAD

**Issue by poscat0x04** [mkloczko/derive-storable#4]
Right now we have 3 typeclasses: `GStorable'` which acts on `Rep a`, `Storable` which is already defined in `base` and there's `GStorable` which is basically `Storable` but with a default signature and a default implementation. I think it might be beneficial to use the `DerivingVia` to simplify the situation.

We could remove the typeclass `GStorable` altogether and rename `GStorable'` into `GStorable` and create a dummy newtype `Generically` which implements the `Storable` class using `GStorable`. This newtype can be used to derive `Storable` for any datatype that implements `GStorable` with the help of `DerivingVia`. (This is what [generic-data](https://hackage.haskell.org/package/generic-data) is doing)

```Haskell
newtype Generically a = Generically { unGenerically :: a }

instance GStorable a => Storable (Generically a) where
  ...

data MyData = MyData 
  { ...
  }
  deriving Storable via Generically MyData
```

**Comment by mkloczko** [comment]
Thanks, will look into it!

**Comment by mkloczko** [comment]
Thanks for the pull request! For now there're two small issues - backward compatibility/design and how does the solution relate to ~performance and~ (performance is good) the plugin.

There was an idea that one could add multiple memory layouts per one data-type, and for that this strategy seems good. Would it be okay if the pull request was merged into a deriving-via branch for now ?

EDIT: Got two tests this week and another next week, so I'm not sure if I'll be able to check everything right now. I'll try to check the performance.

**Comment by poscat0x04** [comment]
Yeah, I'm fine with that. Do I need to open another PR?

**Comment by mkloczko** [comment]
No need! For now will leave this issue open - thank you for the contribution!

**Comment by mkloczko** [comment]
Closing for now, will reopen during redesign.
