### ISSUE TITLE
Why does this depend on GStorable for member types rather than Storable

### ISSUE THREAD

**Issue by expipiplus1** [mkloczko/derive-storable#6]
For example if I have the following:

```haskell

data Bar = Bar
instance Storable Bar where

data Foo = Foo Bar
  deriving (Generic, GStorable)
```

this fails with `No instance for (GStorable Bar)`, however I would expect this to use the Storable instance available.

**Comment by mkloczko** [comment]
If K1 instances depended upon Storable instances instead of GStorable this should work. Will spend some time on that during the weekend - might've done things by convention.

**Comment by expipiplus1** [comment]
Thanks!

**Comment by mkloczko** [comment]
It's done, the Instances module is no longer. Bumped to 0.3 due to that. Hopefully there won't be any side effects.

**Comment by expipiplus1** [comment]
Thanks!

**Comment by expipiplus1** [comment]
> Hopefully there won't be any side effects

derive-storable-plugin is broken because it has too strict dependencies on this package! (and the tests require the Instances module)

**Comment by mkloczko** [comment]
Ok, derive-storable-0.3 should work with derive-storable-plugin-0.2.3.1 for now.

**Comment by expipiplus1** [comment]
Thanks!

**Comment by expipiplus1** [comment]
I think this can be closed now, seem to work well for me in my project.

Also, did this impact the plugin in any way?

**Comment by mkloczko** [comment]
Just had to adjust the tests. Ok, closing.

**Comment by expipiplus1** [comment]
cool, thanks again

**Comment by goertzenator** [comment]
Glad to see this relieved, but the README still indicates that all fields must be GStorable.

Also, I'm struggling to get derive-storable working.  A trivial example in the README including imports and compiler extensions would help tremendously.

Edit:  Never mind, there is a nice example and I am blind.
